<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>UpLoad_Existing_SubCact</name>
   <tag></tag>
   <elementGuidId>6c1ce57e-cdf3-4e40-ac56-481fff9208ae</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//input[@id=&quot;subcategoryBulkUpload&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//input[@id=&quot;subcategoryBulkUpload&quot;]</value>
   </webElementProperties>
</WebElementEntity>
